#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t
#+options: broken-links:nil c:nil creator:nil d:(not "LOGBOOK") date:t e:t
#+options: email:nil f:t inline:t num:t p:nil pri:nil prop:nil stat:t tags:t
#+options: tasks:t tex:t timestamp:t title:t toc:t todo:t |:t
#+title: gunrock_jp
#+date: <2019-03-17 Sun>
#+author: MokkeMeguru
#+email: meguru.mokke@gmail.com
#+language: ja
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 25.2.2 (Org mode 9.2.2)
* 概要
Gunrok は オープンドメインな対話システムで、ユーザに寄り添う形にデザインされた social bot です。
我々はより人間らしい bot を目指すため、大規模なユーザの対話データを繰り返しこの bot に与えました。例えば、このシステムは 2018 年度に行われた Amazon Alexa Prize の準決勝期間中に 4万回を超える会話経験を積みました。
内部については、話題の転換や質疑応答といったユーザの様々な振る舞いに対して、文脈に応じて階層的な会話を行うことのできる対話管理システムを適用しました。これに加え、我々は頑強な 3 ステップの自然言語理解のためのモジュール(NLU module)を設計しました。この中の例としては、文の細分化や自動音声認識エラー修正システムを挙げることができます。更に、我々は bot が人間らしい振る舞いをすることができるように、韻律音声合成を行いました。
これらの多くの努力の結果として、この bot は 10月14日に行われたユーザによる 1-5 点評価のアンケート調査によって 3.62 点の評価を得ることができました。加えてこの調査では、平均 22.14 ターン、時間にして 5分 22秒の連続会話を達成することができました。
* 導入
対話システムの研究における一つの重要な課題として、より多くのユーザによってそのシステムが訓練・テストされなければならないことを挙げることができる。これに対処するために、ほとんどの研究者は、クラウドソーシングされたプラットフォーム上で、コストをかけることで彼らのシステムを訓練・評価していました。しかし、そうやって訓練・評価されたシステムは実際の製品に適用した際に不安定な結果を招く可能性がありました。我々は45日の評価期間で、一日に500対話以上のデータを入手し、最終的に開発期間全体(~ 8月 14日)では 487,314 対話を入手することができました。例えば Amazon Echo といった Alexa が搭載されたどのようなマシンにおいても、アメリカ国内ならば我々のシステムを試すことができました。我々のシステムは多様なユーザの大規模なアクセスに対処する必要がありました。
人間は人間同士のコミュニケーションパターンに慣れているため、ほとんどのユーザは人間対人間のコミュニケーションが行えることをシステムに求めると我々は考えています。例えば、 Microsoft Cortana(パーソナルアシスタントの一種) はソーシャルコンテンツに対処することができないということが知られていますが、ユーザの発言の30％はソーシャルコンテンツを求めています。
