#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t
#+OPTIONS: broken-links:nil c:nil creator:nil d:(not "LOGBOOK") date:t e:t
#+OPTIONS: email:nil f:t inline:t num:t p:nil pri:nil prop:nil stat:t tags:t
#+OPTIONS: tasks:t tex:t timestamp:t title:t toc:t todo:t |:t
#+TITLE: KB-KG-research-roadmap
#+DATE: <2019-06-18 火>
#+AUTHOR: meguru
#+EMAIL: meguru@meguru-Latitude-7390
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 26.1 (Org mode 9.1.9)

* what is this?
  knowledge base と knowledge graph に関する論文調査のロードマップ。これに従って要約記事を作成していく。
  
* roadmap 


** WTF is a knowledge graph ? 
   knowledge graph と knowledge base の違いについて触れている(タイトルのWTFはどう考えても what the f**k だと思われるのだが、果たして)。サブタイトルは ~Unpicking a tangle of terminology to conclude it’s semantic, smart and alive.~ となっており、直訳すると ~それは意味論的で、賢くそして生き生きとしたものである専門用語のもつれを解きほぐします~  のような雰囲気になると思われる。つまりわけのわからない、意味が時とともに変わってしまう専門用語である knowledge graph について解説する、という風に捉えられる。

   特にこの記事で引用されている論文は、Towards a Definition of Knowledeg Graph というもので、ここが記事が書かれた現在(2018年)のKnowledge Graph の定義であるとしている。
   
   #+begin_quote
   A knowledge graph acquires and integrates information into a ontology and applies a reasoner to derive new knowledge.
   #+end_quote

   #+begin_quote
   Knowledge Graph は情報を所得しontology に統合し、推論を用いて新しい知識を導き出すものを指します。
   #+end_quote

   これが記事で最も重要視している Knowledge Graph の定義で、この記事の残りの部分はこの文言に登場する用語の解説に割かれている。
   
   [[https://hackernoon.com/wtf-is-a-knowledge-graph-a16603a1a25f][url]]

** Towards a Definition of Knowledge Graphs 
   knowledge graph の定義についての論文。knowledge graph が研究やビジネスの場に上がってきているものの、それはknowledge graph の一部のみを指すことが多いため、この用語の定義をしなければならないとしている。以下 abstract の意訳。

#+begin_quote   
   一般に彼らが、knowledge graph としてみなしているものは、 semantic web technologies (意味論的Web 技術…？)、linked data (おそらくSEOや推薦アルゴリズムなどを指している)、large-scale data analytics (大規模データ解析)、 cloud computing である。彼らが knowledge graph の例として取り上げている人気の、そして影響力のあるものは Google Knowledge Graph(2012) であり、これを受けて彼らは特に定義することなくKnowledge Graphというものを研究してきた。
   
   しかし Knowledge Graph に多義的な解釈が存在しているせいで、これの発展は阻害され続けてきている。多くの研究論文は、Google Knowledge Graph を参考にしていますが、Google Knowledge Graph自身で使われている技術に関して公式な文書は存在しない。
   
   我々はコンセプトや技術を学術及び商業の舞台で広めていくための理想的な前提条件として、曖昧さのないある特定の定義が必要であると考えている。よって本論文では、この曖昧さを残してきた歴史とその多義性を考慮しつつ、Knowledge Graph とはなにかを定義するために議論する。
   
   本論文の目標は、この話題についての議論の基礎として機能すること、彼らのKnowledge Graph に関するビジョンの共通項を見出し彼らに貢献できる Knowledge Graph の定義を提案することだ。
#+end_quote

  
** DeepDive
   半手動 knowledge base 構築システムについての論文。読むのは全体の論文ではなく(205ページあるので時間が足りない)、その要約の論文。


   DeepDive は専門家 (domain expert) からのルールや修正を反映して自動的に entity 間の relation を取り出し、それを knowledge base の形に落とし込む (Gibbs sampling などを使って relation を周辺化するようだ)。既存研究と比較したいところは、これは自動的に knowledge base を作りたいわけではなく、例えばIBM Watson のような人力の作業を含む knowledge base 作成のコンテクストで、どれだけ人力を必要な部分ににのみ割り当てることができるか、という問題を最適化するための枠組みであるという点だろう。

   [[https://cs.stanford.edu/people/chrismre/papers/deepdive_highlight.pdf][url]]
